GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crm TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA crm TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA crm TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA crm TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT USAGE, SELECT ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm GRANT ALL ON TABLES TO service_role;
NOTIFY pgrst, 'reload schema';