// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugzdwmyylqmirrljtuej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnemR3bXl5bHFtaXJybGp0dWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MDkwNDMsImV4cCI6MjA5MTI4NTA0M30.W1sSTE1mn35ephE4hRzGGLKbKKcgscSsIUk-FKErY-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});