// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfsttkwcwfrnkbkmkzwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmc3R0a3djd2Zybmtia21rendyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMxODkzMTYsImV4cCI6MjA5ODc2NTMxNn0.x7L-mWTnz-yxpXkgH-2XqS2Gib9rD7KcchQECgUa53s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage = {
  getItem: (key: string) => typeof window !== 'undefined' ? window.localStorage.getItem(key) : null,
  setItem: (key: string, value: string) => typeof window !== 'undefined' ? window.localStorage.setItem(key, value) : undefined,
  removeItem: (key: string) => typeof window !== 'undefined' ? window.localStorage.removeItem(key) : undefined,
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});